### PR TITLE
fix(windows): use path.posix.sep instead of path.sep to split glob paths

### PR DESCRIPTION
**Pull request by kant2002**
Split here is virtual name, so it's written as `aaa/someDep`, so I just being extra careful and use both slashes.

### CODE REVIEW

**Comment by FowiFlowi** [comment]
@kant2002, thank you for your involvement! Actually, we can't accept PR that doesn't solve an explicit issue or add some value. Although our team and CI don't use the Windows platform at all, we appreciate your steps and will help. Please provide more details about the issue because replacing built-in functionality with some custom chars seems at least weird.

**Comment by kant2002** [comment]
This discovery I don’t remember all details but depDir here is normalized cross platform path with / as path separator. That’s why it’s breaking on Windows when you try to split by \

**Comment by FowiFlowi** [comment]
@kant2002, that makes sense, thanks! Let's start with UNIX-like slashes only, as glob always returns paths with this separator, even on Windows

**Comment by FowiFlowi** [comment]
So we can just replace `path.sep` with `path.posix.sep`

**Comment by kant2002** [comment]
It was a long time ago. So it’s possible that it was mix of Windows/*Nix paths. I may try in near future

**Comment by FowiFlowi** [comment]
I've checked the code. The inputs are always glob paths, so it should work correctly

**Comment by kant2002** [comment]
Let’s try then. I made suggested changes.

**Comment by FowiFlowi** [comment]
@kant2002, let me some time to sync with upstream, turn on CI for this repo, and then I'll accept your changes

**Review by FowiFlowi — APPROVED** [review]

**Comment by FowiFlowi** [comment]
@kant2002 accepted. Sorry for the delay. We are still enhancing and testing our CI setup for the opensource, which takes some time. By the way, you are the first contributor with an accepted PR, congratulations :)

**Comment by kant2002** [comment]
I’m glad that contributions start flowing into this repo. Hopefully we as a community will have something more substantial to show

**Pull request merged**
